In [32]:
import pandas as pd
import seaborn as sbn
import matplotlib.pyplot as plt
import sqlalchemy
import psycopg2

Pandas → Data handling and analysis.

Seaborn → Beautiful statistical visualizations.

Matplotlib → General plotting and chart creation.

SQLAlchemy → Database connection and 
ORM toolkit.

Psycopg2 → PostgreSQL database connector.

In [33]:
df = pd.read_csv("customerbehaviour.csv")

In [34]:
df.head(10)

,Age,Annual_Income,Spending_Score,Monthly_Visits,Gender,Preferred_Product
0,56,26102,85,6,Female,Clothing
1,46,70336,75,18,Male,Home
2,32,105314,36,10,Male,Groceries
3,60,46641,99,5,Female,Electronics
4,25,54584,19,10,Male,Electronics
5,38,52745,20,12,Male,Electronics
6,56,43093,57,2,Male,Clothing
7,36,86105,18,13,Male,Sports
8,40,71885,47,8,Male,Home
9,28,56631,49,2,Female,Groceries

In [35]:
df.describe(include='all')

,Age,Annual_Income,Spending_Score,Monthly_Visits,Gender,Preferred_Product
count,350.000000,350.000000,350.000000,350.000000,350,350
unique,NaN,NaN,NaN,NaN,2,5
top,NaN,NaN,NaN,NaN,Male,Sports
freq,NaN,NaN,NaN,NaN,191,83
mean,41.202857,71213.274286,49.571429,9.522857,NaN,NaN
std,13.422450,29311.239749,29.602801,5.584290,NaN,NaN
min,18.000000,20412.000000,1.000000,1.000000,NaN,NaN
25%,30.000000,45981.750000,24.000000,5.000000,NaN,NaN
50%,42.000000,71990.500000,51.000000,9.000000,NaN,NaN
75%,52.000000,97945.500000,75.000000,14.000000,NaN,NaN
max,64.000000,119835.000000,99.000000,19.000000,NaN,NaN

In [36]:
df.isnull().sum()

Age                  0
Annual_Income        0
Spending_Score       0
Monthly_Visits       0
Gender               0
Preferred_Product    0
dtype: int64

In [37]:
df.columns

Index(['Age', 'Annual_Income', 'Spending_Score', 'Monthly_Visits', 'Gender',
       'Preferred_Product'],
      dtype='object')

In [38]:
df.columns = df.columns.str.lower()
print(df.columns)
df.head()

Index(['age', 'annual_income', 'spending_score', 'monthly_visits', 'gender',
       'preferred_product'],
      dtype='object')

,age,annual_income,spending_score,monthly_visits,gender,preferred_product
0,56,26102,85,6,Female,Clothing
1,46,70336,75,18,Male,Home
2,32,105314,36,10,Male,Groceries
3,60,46641,99,5,Female,Electronics
4,25,54584,19,10,Male,Electronics

In [51]:
print(f'Maximum Annual Income = {df["annual_income"].max()}')
print(f'Minimum annual income = {df['annual_income'].min()}')

Maximum Annual Income = 119835
Minimum annual income = 20412

salary maximum minimum finding from the dataset

In [55]:
df['income_segment'] = pd.qcut(
    df['annual_income'],
    q=3,
    labels=['low income', 'medium income', 'high income']
)
print(df[['income_segment','annual_income']])

    income_segment  annual_income
0       low income          26102
1    medium income          70336
2      high income         105314
3       low income          46641
4       low income          54584
..             ...            ...
345  medium income          87641
346  medium income          56395
347     low income          42700
348  medium income          54620
349     low income          40559

[350 rows x 2 columns]

Converting the annual_income into equal 4 segment

In [58]:
df['spending_segment'] = pd.qcut(
    df['spending_score'],
    q=3,
    labels=['low spender', 'medium spender', 'high spender']
)
print(df[['spending_segment','spending_score']])

    spending_segment  spending_score
0       high spender              85
1       high spender              75
2     medium spender              36
3       high spender              99
4        low spender              19
..               ...             ...
345   medium spender              37
346      low spender              11
347     high spender              77
348      low spender               3
349   medium spender              33

[350 rows x 2 columns]

In [59]:
df['age_segment'] = pd.cut(
    df['age'],
    bins=[0, 30, 50, 100],
    labels=['young', 'adult', 'senior'])
print(df[['age_segment','age']])

    age_segment  age
0        senior   56
1         adult   46
2         adult   32
3        senior   60
4         young   25
..          ...  ...
345       adult   48
346      senior   52
347       adult   50
348       adult   38
349       adult   49

[350 rows x 2 columns]