In [155]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [156]:
datasetone = pd.read_csv(r"C:\Users\Iman bohare\Desktop\A\file.csv")

In [157]:
datasetone

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

Analyze Dataframe

>Head():-

Shows first N rows in the data(default N = 5)

In [158]:
datasetone.head(10)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,1/1/2012 7:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,1/1/2012 8:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,1/1/2012 9:00,-1.3,-3.1,88,15,4.0,101.20,Fog

.Shape():-
Shows total number of rows and columns

In [159]:
datasetone.shape

(8784, 8)

.index() :-
attribiute provides the index of dataframe

In [160]:
datasetone.tail(5)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

.columns :-
shows the name of each columns

In [161]:
datasetone.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

.dtypes :- 
shows the datatypes of eacch columns

In [162]:
datasetone.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

.unique() :-
shows all the unique values can be apply on a single columns only on the whole dataframe

In [163]:
print(f' the weather one :{datasetone['Weather'].unique()}')

 the weather one :['Fog' 'Freezing Drizzle,Fog' 'Mostly Cloudy' 'Cloudy' 'Rain'
 'Rain Showers' 'Mainly Clear' 'Snow Showers' 'Snow' 'Clear'
 'Freezing Rain,Fog' 'Freezing Rain' 'Freezing Drizzle' 'Rain,Snow'
 'Moderate Snow' 'Freezing Drizzle,Snow' 'Freezing Rain,Snow Grains'
 'Snow,Blowing Snow' 'Freezing Fog' 'Haze' 'Rain,Fog' 'Drizzle,Fog'
 'Drizzle' 'Freezing Drizzle,Haze' 'Freezing Rain,Haze' 'Snow,Haze'
 'Snow,Fog' 'Snow,Ice Pellets' 'Rain,Haze' 'Thunderstorms,Rain'
 'Thunderstorms,Rain Showers' 'Thunderstorms,Heavy Rain Showers'
 'Thunderstorms,Rain Showers,Fog' 'Thunderstorms' 'Thunderstorms,Rain,Fog'
 'Thunderstorms,Moderate Rain Showers,Fog' 'Rain Showers,Fog'
 'Rain Showers,Snow Showers' 'Snow Pellets' 'Rain,Snow,Fog'
 'Moderate Rain,Fog' 'Freezing Rain,Ice Pellets,Fog'
 'Drizzle,Ice Pellets,Fog' 'Drizzle,Snow' 'Rain,Ice Pellets'
 'Drizzle,Snow,Fog' 'Rain,Snow Grains' 'Rain,Snow,Ice Pellets'
 'Snow Showers,Fog' 'Moderate Snow,Blowing Snow']

Columns:- Shows the columns of the table

info:- shows information about row and columns

describe:- explain about the present data types

In [164]:
print(datasetone.columns)
print()
print()
print()
print(datasetone.info())
print()
print()
print()
print(datasetone.describe())
print()
print()
print()

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB
None



            Temp_C  Dew Point Temp_C    Rel Hum_%  Wind Speed_km/h  \
count  8784.000000       8784.000000  8784.000000      8784.000000
mean      8.798144          2.555294    67.431694        14.945469
std      11.687883         10.883072    16.918881         8.688696
min     -23.300000        -28.500000    18.000000         0.000000
25%       0.100000         -5.900000    56.000000         9.000000
50%       9.300000          3.300000    68.000000        13.000000
75%      18.800000         11.800000    81.000000        20.000000
max      33.000000         24.400000   100.000000        83.000000

       Visibility_km    Press_kPa
count    8784.000000  8784.000000
mean       27.664447   101.051623
std        12.622688     0.844005
min         0.200000    97.520000
25%        24.100000   100.560000
50%        25.000000   101.070000
75%        25.000000   101.590000
max        48.300000   103.650000

.Count :-
Total number non-null values in each column can be applied on single column as well as whole dataframe

In [165]:
datasetone.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

.value_counts :-
shows the unique value with their count can be applied only on single column onlyone

In [166]:
datasetone['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [167]:
#groupby
datasetone.groupby('Weather').get_group('Clear')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

The mean visibility:-

Variance

Plotting Datetime Temprature

In [168]:
# import pandas as pd
# import matplotlib.pyplot as plt
# datasetone = pd.read_csv(r"C:\Users\Iman bohare\Desktop\A\file.csv")
# plt.figure(figsize=(10,6))
# plt.plot(datasetone["Date/Time"], datasetone["Temp_C"])
# plt.xlabel("Date/Time")
# plt.ylabel("Temperature (°C)")
# plt.title("Temperature Trend")
# plt.xticks(rotation=45)
# plt.show()

In [169]:
datasetone.shape

(8784, 8)

In [170]:
datasetone.sample(10)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
1242,2/21/2012 18:00,1.9,-6.1,55,9,25.0,100.54,Cloudy
7562,11/11/2012 2:00,3.0,-7.8,45,11,25.0,102.33,Cloudy
7544,11/10/2012 8:00,0.4,-4.9,68,13,24.1,102.32,Clear
6420,9/24/2012 12:00,15.0,5.7,54,20,48.3,101.37,Mainly Clear
8434,12/17/2012 10:00,0.5,-0.8,91,20,3.6,100.78,"Snow,Fog"
2440,4/11/2012 16:00,9.5,1.4,57,20,24.1,100.82,Mostly Cloudy
2022,3/25/2012 6:00,3.8,-0.9,71,15,24.1,100.76,Rain Showers
8452,12/18/2012 4:00,0.5,-0.8,91,24,11.3,100.15,Rain
3719,6/3/2012 23:00,13.3,6.9,65,30,25.0,100.31,Mostly Cloudy
522,1/22/2012 18:00,-10.4,-16.1,63,19,19.3,102.52,Mostly Cloudy

In [171]:
datasetone.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

Explitting day month year of date

In [172]:
datasetone['DAY']=datasetone['Date/Time'].str.split('/').str[0]
datasetone['MONTH']=datasetone['Date/Time'].str.split('/').str[1]
datasetone['YEAR']=datasetone['Date/Time'].str.split('/').str[2]
datasetone

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather,DAY,MONTH,YEAR
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog,1,1,2012 0:00
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog,1,1,2012 1:00
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",1,1,2012 2:00
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",1,1,2012 3:00
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog,1,1,2012 4:00
...,...,...,...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow,12,31,2012 19:00
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow,12,31,2012 20:00
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow,12,31,2012 21:00
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow,12,31,2012 22:00
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow,12,31,2012 23:00

Changing Then Column Date/Time deleting because not necessary

In [173]:
datasetone = datasetone.drop('Date/Time', axis=1)
datasetone

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather,DAY,MONTH,YEAR
0,-1.8,-3.9,86,4,8.0,101.24,Fog,1,1,2012 0:00
1,-1.8,-3.7,87,4,8.0,101.24,Fog,1,1,2012 1:00
2,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",1,1,2012 2:00
3,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",1,1,2012 3:00
4,-1.5,-3.3,88,7,4.8,101.23,Fog,1,1,2012 4:00
...,...,...,...,...,...,...,...,...,...,...
8779,0.1,-2.7,81,30,9.7,100.13,Snow,12,31,2012 19:00
8780,0.2,-2.4,83,24,9.7,100.03,Snow,12,31,2012 20:00
8781,-0.5,-1.5,93,28,4.8,99.95,Snow,12,31,2012 21:00
8782,-0.2,-1.8,89,28,9.7,99.91,Snow,12,31,2012 22:00
8783,0.0,-2.1,86,30,11.3,99.89,Snow,12,31,2012 23:00

In [174]:
datasetone['DAY'] = datasetone['DAY'].astype(np.int32)
datasetone['MONTH'] = datasetone['MONTH'].astype(int)
datasetone['YEAR'] = datasetone['MONTH'].astype(int)

In [175]:
print(datasetone['YEAR'].dtype)

int64

In [176]:
datasetone['YEAR'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [177]:
datasetone.describe(include='object')

             Weather
count           8784
unique            50
top     Mainly Clear
freq            2106

In [178]:
maximum_weather = datasetone['Weather'].value_counts().idxmax()
print(maximum_weather)

maximum_chance_day = datasetone[datasetone['Weather'] == maximum_weather]
print(maximum_chance_day)

Mainly Clear
      Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  Visibility_km  \
36       1.7              -6.2         56               48           24.1
60     -14.9             -22.6         52               20           24.1
61     -15.1             -22.4         54               22           24.1
62     -14.9             -22.9         50               22           24.1
63     -14.8             -22.2         53               19           24.1
...      ...               ...        ...              ...            ...
8753   -12.1             -15.8         74               28           25.0
8754   -12.6             -16.0         76               24           25.0
8755   -13.4             -16.5         77               26           25.0
8757   -13.8             -16.5         80               20           25.0
8758   -13.7             -16.3         81               19           25.0

      Press_kPa       Weather  DAY  MONTH  YEAR
36        99.21  Mainly Clear    1      2     2
60       101.34  Mainly Clear    1      3     3
61       101.34  Mainly Clear    1      3     3
62       101.38  Mainly Clear    1      3     3
63       101.44  Mainly Clear    1      3     3
...         ...           ...  ...    ...   ...
8753     101.26  Mainly Clear   12     30    30
8754     101.36  Mainly Clear   12     30    30
8755     101.47  Mainly Clear   12     30    30
8757     101.50  Mainly Clear   12     30    30
8758     101.54  Mainly Clear   12     30    30

[2106 rows x 10 columns]

In [181]:
minimum_weather = datasetone['Weather'].value_counts().idxmin()
print(minimum_weather)

minimum_chance_day = datasetone['Weather'].value_counts().idxmin()
print(maximum_chance_day)

Rain Showers,Fog
      Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  Visibility_km  \
36       1.7              -6.2         56               48           24.1
60     -14.9             -22.6         52               20           24.1
61     -15.1             -22.4         54               22           24.1
62     -14.9             -22.9         50               22           24.1
63     -14.8             -22.2         53               19           24.1
...      ...               ...        ...              ...            ...
8753   -12.1             -15.8         74               28           25.0
8754   -12.6             -16.0         76               24           25.0
8755   -13.4             -16.5         77               26           25.0
8757   -13.8             -16.5         80               20           25.0
8758   -13.7             -16.3         81               19           25.0

      Press_kPa       Weather  DAY  MONTH  YEAR
36        99.21  Mainly Clear    1      2     2
60       101.34  Mainly Clear    1      3     3
61       101.34  Mainly Clear    1      3     3
62       101.38  Mainly Clear    1      3     3
63       101.44  Mainly Clear    1      3     3
...         ...           ...  ...    ...   ...
8753     101.26  Mainly Clear   12     30    30
8754     101.36  Mainly Clear   12     30    30
8755     101.47  Mainly Clear   12     30    30
8757     101.50  Mainly Clear   12     30    30
8758     101.54  Mainly Clear   12     30    30

[2106 rows x 10 columns]